### ISSUE TITLE
Add long/int implementation

### ISSUE THREAD

**Issue by jrleeman** [sebnil/FIR-filter-Arduino-Library#2]
Any opposition to a PR that makes the filter work with int or long values and coefficients. This would be a faster operation that all the floating point math.

**Comment by sebnil** [comment]
You are right. Unless it is used on a mcu with floating point support. Anyway, it seems like too big of a change for this library. 

Thank you for the feedback. Maybe it can be done in a fork of this repo?

**Comment by jrleeman** [comment]
Fair - I'll likely implement and ping you back on here. Thanks for this library!
